### ISSUE TITLE
gcc error (gcc yamdi.c -o yamdi -O2 -Wall)

### ISSUE THREAD

**Issue by ouewqa** [ioppermann/yamdi#8]
gcc yamdi.c -o yamdi -O2 -Wall
yamdi.c: In function ‘main’:
yamdi.c:284:51: warning: variable ‘creator’ set but not used [-Wunused-but-set-variable]

**Comment by ioppermann** [comment]
Thanks. Fixed. Not all gcc, clang versions complain, though.
